classOrder = ["Store", "Keep", "GlobalUpdates"]


gitSourceBranch = "main"

[docusaurus]
url = "https://noahrepublic.github.io"
tagline = "The final data saving solution you need"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Easy to start"
description = "API is similar naming to ProfileService super easy to transfer over"

[[home.features]]
title = "Promise based"
description = "Promise based API to know exactly when things are done"

[[home.features]]
title = "Clean, actively maintained code base"
description = "Codebase provides easy to contribute, and to add future functionality"