# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lune = "lune-org/lune@0.8.9"
rojo = "rojo-rbx/rojo@7.4.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "Kampfkarren/selene@0.27.1"
stylua = "johnnymorganz/stylua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
